# Generated by Django 5.0.6 on 2024-06-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(default='x', max_length=255),
            preserve_default=False,
        ),
    ]
